// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeFOQTEGXwFOVniALwZLiR7MM252xeieo',
    appId: '1:299969906157:web:b53ccbadd0038c8dde13e4',
    messagingSenderId: '299969906157',
    projectId: 'aou-clubs',
    authDomain: 'aou-clubs.firebaseapp.com',
    storageBucket: 'aou-clubs.appspot.com',
    measurementId: 'G-Z7NMY50D7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRiCm7l3eqBXNXG4XrEglXiMdIVuuAHGo',
    appId: '1:674025303011:android:b82a9bdf765cb672244ed6',
    messagingSenderId: '674025303011',
    projectId: 'aou-clubs-ccbdd',
    storageBucket: 'aou-clubs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClHXiOCoReoSMe3AtTPgxWqBdznaVcRGA',
    appId: '1:299969906157:ios:09656ee0de78f959de13e4',
    messagingSenderId: '299969906157',
    projectId: 'aou-clubs',
    storageBucket: 'aou-clubs.appspot.com',
    iosBundleId: 'com.example.aouClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClHXiOCoReoSMe3AtTPgxWqBdznaVcRGA',
    appId: '1:299969906157:ios:b49dd6b3aab15ecede13e4',
    messagingSenderId: '299969906157',
    projectId: 'aou-clubs',
    storageBucket: 'aou-clubs.appspot.com',
    iosBundleId: 'com.example.aouClub.RunnerTests',
  );
}
